#!/usr/bin/env bash

Var=$PWD/var

prep() { gawk --source '
{$0=gensub(/\.([^0-9])([a-zA-Z0-9_]*)/,"[\"\\1\\2\"]","g",$0)}
{print gensub(/__/,".","g",$0)}
' -
}

for i in *.awk; do
  if [ $i -nt $Var/$i ]; then
     cat $i | prep > $Var/$i
  fi
done

echo $1
set -x 
if [ -f "$1" ]; then
	echo 1
  AWKPATH="$Var" gawk --source "`cat $1 | prep`"
elif [ "$1" == "hi" ]; then
	echo 2
  git pull
elif [ "$1" == "bye" ]; then
	echo 3
	echo 11
  git commit -am "pushing"
  git push
  git status
else
  usage
fi
