#!/usr/local/bin/gawk -f
# set filetype=awk tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

BEGIN {FS=","}
{ for(I=1;I<=NF;I++) 
    if (NF==1) {
       print $0
       header(I,$I) 
    } else {
       Data[I,NR-1] = $I 
       if (I in Num) {
	 Hi[I] = I > Hi[I] ? $I : Hi[I]
	 Lo[I] = I < Lo[I] ? $I : Lo[I] }}}

END { finale(Data,NR-1,NF) }

func norm(x,c) return (x - Lo(c)) / (Hi[c] - Lo[c] + 10^-32)

func header(txt,pos) {
  if ( txt ~ /</  ) W[pos] = -1
  if ( txt ~ />/  ) W[pos] =  1
  if ( txt ~ /[<>\$]/ ) {
    Num[pos]
    Hi[pos] = -10^32
    Lo[pos] =  10^32 }
}
function dominates(r1,r2, data,   n,c,a,b,s1,s1) {
  n = length(W)
  for (c in W) {
    w  =  W[c]
    a  =  norm(data[r1,c], c)
    b  =  norm(data[r2,c], c)
    s1 =- 10^(w * (a - b) / n)
    s2 =- 10^(w * (b - a) / n)  }
  return s1 / n < s2 / n
}
